name: Generate MASSOOKTV.m3u8

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */10 * * *'  # Setiap 10 jam

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PROXY_PREFIX: ${{ secrets.PROXY_PREFIX }}
      SOURCE_URL_1: ${{ secrets.SOURCE_URL_1 }}
      SOURCE_URL_2: ${{ secrets.SOURCE_URL_2 }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: pip install requests

    - name: Jalankan script sooka
      run: python3 grabmasooktv.py

    - name: Clone repo privat output
      run: |
        git clone --depth=1 https://x-access-token:${{ secrets.TOKEN_PRIVATE }}@github.com/${{ secrets.REPO_PRIVATE }} repo-output
        cp MASSOOKTV.m3u8 repo-output/
      shell: bash

    - name: Push ke repo privat
      run: |
        cd repo-output
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add MASSOOKTV.m3u8
        git commit -m "🆕 Update MASSOOKTV.m3u8 - $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push
