name: Selenium CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  selenium:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. Cache webdriver-manager
      - name: Cache WebDriver
        uses: actions/cache@v4
        with:
          path: .wdm_cache
          key: ${{ runner.os }}-chromedriver-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-chromedriver-

      # 4. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install selenium webdriver-manager

      # 5. Install Chrome (wajib biar ada browser)
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          google-chrome --version
